
clone_folder: c:\projects\OpenSubdiv

branches:
    only:
        - master
        - dev
        - dev_appv

platform:
    #- x86
    - x64

configuration:
    - 14 2015
    #- 12 2013

build_script:
    - cd c:\projects\OpenSubdiv
    - mkdir build
    - cd build
    - cmake --version
    - cmake -G "Visual Studio %Configuration%" -DNO_TBB=1 -DNO_OMP=1 -DNO_CUDA=1 -DNO_PTEX=1 -DNO_DOC=1 -DNO_CLEW=1 -DNO_OPENGL=1 -DNO_OPENCL=1 ..
    - cmake --build . --config Release

test_script:
    - cd c:\projects\OpenSubdiv\build
    - ctest -C Release . --output-on-failure
